// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_message from "./routes/api/message.ts";
import * as $api_reply from "./routes/api/reply.ts";
import * as $api_signup from "./routes/api/signup.ts";
import * as $api_verify_gid from "./routes/api/verify-gid.ts";
import * as $b_board_ from "./routes/b/[board].tsx";
import * as $home_index from "./routes/home/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $m_message_ from "./routes/m/[message].tsx";
import * as $signup from "./routes/signup.tsx";
import * as $CardActionLogin from "./islands/CardActionLogin.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GoogleAuth from "./islands/GoogleAuth.tsx";
import * as $HomeMessageCard from "./islands/HomeMessageCard.tsx";
import * as $HomeShareCard from "./islands/HomeShareCard.tsx";
import * as $Language from "./islands/Language.tsx";
import * as $LoginCard from "./islands/LoginCard.tsx";
import * as $LogoBtn from "./islands/LogoBtn.tsx";
import * as $LogoutBtn from "./islands/LogoutBtn.tsx";
import * as $PasswordSignup from "./islands/PasswordSignup.tsx";
import * as $ReplyDelBtn from "./islands/ReplyDelBtn.tsx";
import * as $SignupCard from "./islands/SignupCard.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/message.ts": $api_message,
    "./routes/api/reply.ts": $api_reply,
    "./routes/api/signup.ts": $api_signup,
    "./routes/api/verify-gid.ts": $api_verify_gid,
    "./routes/b/[board].tsx": $b_board_,
    "./routes/home/index.tsx": $home_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/m/[message].tsx": $m_message_,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/CardActionLogin.tsx": $CardActionLogin,
    "./islands/Counter.tsx": $Counter,
    "./islands/GoogleAuth.tsx": $GoogleAuth,
    "./islands/HomeMessageCard.tsx": $HomeMessageCard,
    "./islands/HomeShareCard.tsx": $HomeShareCard,
    "./islands/Language.tsx": $Language,
    "./islands/LoginCard.tsx": $LoginCard,
    "./islands/LogoBtn.tsx": $LogoBtn,
    "./islands/LogoutBtn.tsx": $LogoutBtn,
    "./islands/PasswordSignup.tsx": $PasswordSignup,
    "./islands/ReplyDelBtn.tsx": $ReplyDelBtn,
    "./islands/SignupCard.tsx": $SignupCard,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
